repos:
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: '2.2.21'
    hooks:
      - id: checkov
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0
    hooks:
      - id: terraform_docs
      - id: terraform_fmt
      - id: infracost_breakdown
        args:
          - --args=--path=./
          - --args=--usage-file=infracost-usage.yml
          - --hook-config='.totalHourlyCost|tonumber < 0.5'
          - --hook-config='.projects[].diff.totalMonthlyCost|tonumber < 200'
          - --hook-config='.currency == "EUR"'
        verbose: true